-- MySQL Script generated by MySQL Workbench
-- Mon Aug 13 13:36:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Loncoto_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Loncoto_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Loncoto_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Loncoto_db` ;

-- -----------------------------------------------------
-- Table `Loncoto_db`.`Intervenant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Intervenant` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Intervenant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `telephone` INT NOT NULL,
  `specialité` VARCHAR(50) NULL,
  `cvId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telephone_UNIQUE` (`telephone` ASC) VISIBLE,
  UNIQUE INDEX `cvId_UNIQUE` (`cvId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Famille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Famille` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Famille` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Sous_Famille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Sous_Famille` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Sous_Famille` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `familleId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `RelFamille_idx` (`familleId` ASC) VISIBLE,
  CONSTRAINT `RelFamille`
    FOREIGN KEY (`familleId`)
    REFERENCES `Loncoto_db`.`Famille` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Article` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `sousFamilleId` INT NULL,
  `description` VARCHAR(100) NOT NULL,
  `ficheTech` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `RelSousFamille_idx` (`sousFamilleId` ASC) VISIBLE,
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE,
  CONSTRAINT `RelSousFamille`
    FOREIGN KEY (`sousFamilleId`)
    REFERENCES `Loncoto_db`.`Sous_Famille` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Client` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entreprise` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telephone` INT NOT NULL,
  `siret` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telephone_UNIQUE` (`telephone` ASC) VISIBLE,
  UNIQUE INDEX `siret_UNIQUE` (`siret` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Site` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Site` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `adresse_UNIQUE` (`adresse` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Batiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Batiment` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Batiment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `siteId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `RelSite_idx` (`siteId` ASC) VISIBLE,
  CONSTRAINT `RelSite`
    FOREIGN KEY (`siteId`)
    REFERENCES `Loncoto_db`.`Site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Etage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Etage` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Etage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `batimentId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `RelBatiment_idx` (`batimentId` ASC) VISIBLE,
  CONSTRAINT `RelBatiment`
    FOREIGN KEY (`batimentId`)
    REFERENCES `Loncoto_db`.`Batiment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Salle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Salle` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Salle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(70) NOT NULL,
  `etageId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `RelEtage_idx` (`etageId` ASC) VISIBLE,
  CONSTRAINT `RelEtage`
    FOREIGN KEY (`etageId`)
    REFERENCES `Loncoto_db`.`Etage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Materiel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Materiel` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Materiel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serialNo` VARCHAR(45) NOT NULL,
  `clientId` INT NOT NULL,
  `salleId` INT NOT NULL,
  `articleId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `RelArticle_idx` (`articleId` ASC) VISIBLE,
  INDEX `RelClient_idx` (`clientId` ASC) VISIBLE,
  INDEX `RelSalle_idx` (`salleId` ASC) VISIBLE,
  UNIQUE INDEX `serialNo_UNIQUE` (`serialNo` ASC) VISIBLE,
  CONSTRAINT `RelArticle`
    FOREIGN KEY (`articleId`)
    REFERENCES `Loncoto_db`.`Article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RelClient`
    FOREIGN KEY (`clientId`)
    REFERENCES `Loncoto_db`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RelSalle`
    FOREIGN KEY (`salleId`)
    REFERENCES `Loncoto_db`.`Salle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Intervention`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Intervention` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Intervention` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datePlanification` DATETIME NOT NULL,
  `dateRealisation` DATETIME NOT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `commentaireIntervenant` VARCHAR(100) NULL,
  `descriptionPanne` VARCHAR(100) NOT NULL,
  `intervenantId` INT NOT NULL,
  `materielId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `RelIntervenant_idx` (`intervenantId` ASC) VISIBLE,
  INDEX `RelMateriel_idx` (`materielId` ASC) VISIBLE,
  CONSTRAINT `RelIntervenant`
    FOREIGN KEY (`intervenantId`)
    REFERENCES `Loncoto_db`.`Intervenant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RelMateriel`
    FOREIGN KEY (`materielId`)
    REFERENCES `Loncoto_db`.`Materiel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`Image` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`Image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(70) NOT NULL,
  `interventionId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  INDEX `RelIntervention_idx` (`interventionId` ASC) VISIBLE,
  CONSTRAINT `RelIntervention`
    FOREIGN KEY (`interventionId`)
    REFERENCES `Loncoto_db`.`Intervention` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loncoto_db`.`RelClientSite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loncoto_db`.`RelClientSite` ;

CREATE TABLE IF NOT EXISTS `Loncoto_db`.`RelClientSite` (
  `clientId` INT NOT NULL,
  `siteId` INT NOT NULL,
  PRIMARY KEY (`clientId`, `siteId`),
  INDEX `RelSite_idx` (`siteId` ASC) VISIBLE,
  CONSTRAINT `RelClient`
    FOREIGN KEY (`clientId`)
    REFERENCES `Loncoto_db`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RelSite`
    FOREIGN KEY (`siteId`)
    REFERENCES `Loncoto_db`.`Site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
